### ISSUE TITLE
Problem with downloading on Raspberry Pi

### ISSUE THREAD

**Issue by legatm** [neliogodoi/MicroPython-SI1145#4]
I start by typing this into the command: git clone https://github.com/THP-JOE/Python_SI1145
after that i type: cd Phyton_SI1145
the i try to download it with: sudo python setup.py install

Then i get this notification:
Extracting in /tmp/tmpaGoiHt
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools()
  File "/home/pi/Python_SI1145/ez_setup.py", line 130, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/pi/Python_SI1145/ez_setup.py", line 110, in _do_download
    _build_egg(egg, archive, to_dir)
  File "/home/pi/Python_SI1145/ez_setup.py", line 59, in _build_egg
    with archive_context(archive_filename):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/pi/Python_SI1145/ez_setup.py", line 90, in archive_context
    with get_zip_class()(filename) as archive:
  File "/usr/lib/python2.7/zipfile.py", line 793, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 834, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

PLS HELP

**Comment by neliogodoi** [comment]
If you want to use the SI1145 module on the Raspberry Pi, obtain the module at https://pypi.org/project/SI1145/
